### ISSUE TITLE
Redirect unavailable episodes from southpark.cc to alternative provider

### ISSUE THREAD

**Issue by andrestaht** [syyfilis/random-south-park-episode#35]
These episodes cannot be streamed from [southpark.cc](http://southpark.cc.com/) 
- http://southpark.cc.com/full-episodes/s14e05-200
- http://southpark.cc.com/full-episodes/s14e06-201

Would be nice if unavailabe episodes (currently only these) would be streamed from [kisscartoon](kisscartoon.me) or some other provider.

**Comment by ukupat** [comment]
We could track down all the episodes that are not shown in Estonia (making our bets on that) and set a property for every episode object in Firebase that this should be opened in Kiss Cartoon.

@syyfilis what do you think?

**Comment by ukupat** [comment]
Not sure if this is a good idea, because users can go mad when they see Kiss Cartoon though they have seen other episodes @ CC.

**Comment by ukupat** [comment]
Dropping the topic, related to #14 issue
